modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="simplest_copper_gear"
version="1.0.6"
displayName="Simplest Copper Gear"
authors="Team Solar"
description='''Copper armor and tools.'''
logoFile="icon.png"

[[dependencies.simplest_copper_gear]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"


[[dependencies.simplest_copper_gear]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"